### ISSUE TITLE
Doesn't work with React 16.7

### ISSUE THREAD

**Issue by Bersam** [mohebifar/react-persian#15]
```bash
Cannot read property 'bool' of undefined
TypeError: Cannot read property 'bool' of undefined
    at ./node_modules/react-persian/lib/PersianNumber.js:97:32
    at Object.<anonymous> (./node_modules/react-persian/lib/PersianNumber.js:112:3)
```

**Comment by naixatwork** [comment]
Im having the same problem

**Comment by pedram6195** [comment]
me to 😢

**Comment by jedimahdi** [comment]
Same here

**Comment by yasin6606** [comment]
same problem

**Comment by vahidimani** [comment]
Same issue

**Comment by Hosein-mh** [comment]
same issue

**Comment by maniyeganeh** [comment]
same issue

**Comment by mehdi-eti** [comment]
install prop-types
